### ISSUE TITLE
Spaces in directories

### ISSUE THREAD

**Issue by LloydLabs** [lodi-g/codeserve#1]
For some reason, if a directory has a space in the served directory it can't list the contents of the directory.

**Comment by lodi-g** [comment]
It seems to be working fine for me with this directory:

```
$ tree test\ with\ spaces 
test with spaces
└── hello.c
```

There is no errors and files are served.

**Comment by LloydLabs** [comment]
Looking at the rendering it seems to be an issue there. It unescapes itself. It needs to be escaped so it's not rendered as HTML. Could also be an XSS issue here with a specially crafted directory.

`<a href="x" (potentially="" y)="">y (y y)/</a>`

**Comment by lodi-g** [comment]
Fixed in 3406aa3.
